"""
THIS CODE IS AUTOGENERATED
PLEASE, DO NOT USE FUNCTIONS create_table, add_column, delete_table, delete_column
USE create_model, add_field, delete_model, delete_field INSTEAD
GENERATED AT Oct 17 2021 14:48:19
"""

from migration_functions import *


def run():
    
    create_table("user", {'first_name': {'type': 'text', 'null': False, 'default': None, 'pk': False}, 'last_name': {'type': 'text', 'null': False, 'default': None, 'pk': False}, 'patronymic': {'type': 'text', 'null': False, 'default': None, 'pk': False}, 'id': {'type': 'INTEGER', 'null': False, 'default': 1, 'pk': True}})
                    

def run_migration():
    actions = [
        run
    ]

    for action in actions:
        action()
