"""
THIS CODE IS AUTOGENERATED
PLEASE, DO NOT USE FUNCTIONS create_table, add_column, delete_table, delete_column
USE create_model, add_field, delete_model, delete_field INSTEAD
GENERATED AT May 02 2022 18:36:06
"""

from migration_functions import *


def run():
    
    delete_column("user", "age")
                    

def run_migration():
    actions = [
        run
    ]

    for action in actions:
        action()
